version: "3"

services:

  sender:
    build: ./build/sender
    env_file :
        - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /glpi_bot_volume:/app/sender
    # ports:
    #   - 3000:3000
    restart: always

  notifier:
    build: ./build/notifier
    env_file :
        - .env
    # ports:
    #   - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /glpi_bot_volume:/app/notifiler
    depends_on:
      - sender
    restart: always
